manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: Yoichi-Maribao  # <-- 新しく追加するリモート名

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main

    - name: az1uball-test  # <-- zmk-az1uball-driver を az1uball-test に置き換え
      remote: Yoichi-Maribao  # <-- 新しいリモート名を指定
      revision: main
      path: modules/az1uball-test  # プロジェクトを配置するパスを指定

  self:
    path: config
