manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: yummyKB  # <-- 新しく追加するリモート名
      url-base: https://github.com/yummyKB

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: zmk-az1uball-driver  # <-- zmk-az1uball-driver を az1uball-test に置き換え
      remote: yummyKB  # <-- 新しいリモート名を指定
      revision: main
      #path: modules/az1uball-test  # プロジェクトを配置するパスを指定

  self:
    path: config
